### ISSUE TITLE
Code Highlighting breaks on default light media 

### ISSUE THREAD

**Issue by Muhammed-Abdullah-Shaikh** [ABD-01/furo50#7]
The default browser appearance is light.
When switched to dark mode, using the theme icon, the code highlighting break.

## Expected Behavior
The background color in pre tag should be dark

## Actual Behavior
The background color in pre tag is light even if dark dome is selected

## Steps to Reproduce the Problem
N.A.

## Any logs, error output, etc?

Current Behavior:
![image](https://github.com/user-attachments/assets/a4202832-f2e7-4ea2-98c6-4b094ee86617)

Expected should be

![image](https://github.com/user-attachments/assets/60730020-21c4-41be-919f-a8a3ba455751)

## What versions of software are you using?

  - Furo50 Version: `1.0.0-alpha.1`
  - Platform: Windows10
  - Browser: Microsoft Edge 128.0.2739.42

**Comment by ABD-01** [comment]
Ignore the bot.
I need to fix that workflow

**Comment by Muhammed-Abdullah-Shaikh** [comment]
I believe it is caused by 
https://github.com/ABD-01/furo50/blob/a48d44801a7d4d3ace55404849402bba4e82e310/src/furo50/_static/css/cs50.css#L2-L10
